apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: py-new-ns-0405
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: py-new-ns-0405 
  name: py-new-ns-0405
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: py-new-ns-0405
    weight: 100 
