apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: py-new-ns-0405
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: py-new-ns-0405 
  name: py-new-ns-0405
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: py-new-ns-0405 
